---
components:
  - type: LDR20
    parent_link: mount_link
    xyz: -0.19 0.0 0.0
    rpy: 0.0 0.0 0.0

  - type: LDR06
    parent_link: mount_link
    xyz: -0.19 0.0 0.07
    rpy: 0.0 0.0 0.0
    name: rplidar

  - type: CAM01
    parent_link: mount_link
    xyz: 0.2 0.0 0.05
    rpy: 0.0 0.0 0.0
    name: camera

  - type: WCH01
    parent_link: front_bumper_link
    xyz: -0.01 0.0 0.0
    rpy: 0.0 0.0 0.0
