---
/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.08
    profile: false
    max_hamming: 0

    detector:
      threads: 1
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    tag:
      ids: [0, 1]
      frames: [main_apriltag_link, backup_apriltag_link]
      sizes: [0.08, 0.08]
