controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    fr3_gripper_controller:
      type: position_controllers/GripperActionController

fr3_arm_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
fr3_gripper_controller:
  ros__parameters:
    joint: fr3_finger_joint1
